# Generated by Django 4.2 on 2023-08-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bookid_favorites',
        ),
        migrations.AddField(
            model_name='user',
            name='bookid_favorites',
            field=models.ManyToManyField(blank=True, max_length=700, null=True, related_name='bookid_favorites', to='app.book', verbose_name='Избранные книги'),
        ),
    ]
