# Generated by Django 4.2 on 2023-05-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='Имя'),
        ),
    ]
