# Generated by Django 4.2 on 2023-06-04 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_booking_book_id_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='id_book',
        ),
        migrations.AddField(
            model_name='book',
            name='bookings',
            field=models.ForeignKey(blank=True, max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='app.booking', verbose_name='id_книги'),
        ),
    ]
