# Generated by Django 4.2 on 2023-08-30 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_book_bookmarker_alter_book_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='bookmarker',
        ),
        migrations.AlterField(
            model_name='book',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL, verbose_name='Кто забронировал'),
        ),
    ]
