# Generated by Django 4.2 on 2023-05-23 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_language_remove_book_language_book_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='languages',
        ),
        migrations.AddField(
            model_name='book',
            name='languages',
            field=models.ForeignKey(blank=True, max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='app.language', verbose_name='языки'),
        ),
    ]
