# Generated by Django 4.2 on 2023-06-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_user_bookid_user_bookid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookings',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Бронь книги'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='bookid',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.AddField(
            model_name='user',
            name='bookid',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='id книги'),
        ),
    ]
