# Generated by Django 4.2 on 2023-06-05 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_book_bookings_remove_user_bookid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='userid',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='id Пользователя'),
        ),
    ]
