# Generated by Django 4.2 on 2023-08-30 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_book_bookmarker_alter_book_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bookmarker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarker_book', to=settings.AUTH_USER_MODEL, verbose_name='Кто добавил в избранное'),
        ),
    ]
