# Generated by Django 4.2 on 2023-04-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_genrebook'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GenreBook',
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(to='app.genre', verbose_name='жанры'),
        ),
        migrations.AddField(
            model_name='genre',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
    ]
