# Generated by Django 4.2 on 2023-07-14 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_book_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='app.book', verbose_name='Книга'),
        ),
    ]
