# Generated by Django 4.2 on 2023-06-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_book_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='user_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Копия'),
        ),
    ]
