# Generated by Django 4.2 on 2023-04-14 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_genrebook_remove_book_genre_book_genres_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='description',
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(max_length=30, null=True, verbose_name='Язык'),
        ),
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.CharField(max_length=10, null=True, verbose_name='Год издания'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(related_name='genres', to='app.genre', verbose_name='жанры'),
        ),
    ]
