# Generated by Django 4.2 on 2023-08-30 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_book_bookmarker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='bookmarker',
        ),
        migrations.AlterField(
            model_name='user',
            name='bookid_favorites',
            field=models.ManyToManyField(blank=True, max_length=700, null=True, related_name='favorited_by_users', to='app.book', verbose_name='Избранные книги'),
        ),
    ]
