# Generated by Django 4.2 on 2023-06-05 22:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_book_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bookid',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=6),
        ),
    ]
