# Generated by Django 4.2 on 2023-08-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_book_bookmarker_alter_book_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bookid_favorites',
        ),
        migrations.AddField(
            model_name='user',
            name='bookid_favorites',
            field=models.TextField(blank=True, null=True),
        ),
    ]
