# Generated by Django 4.2 on 2023-06-05 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_user_bookid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='bookid',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='id книги'),
        ),
    ]
