# Generated by Django 4.2 on 2023-06-05 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_book_user_id_alter_user_bookid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bookid',
            field=models.TextField(blank=True, null=True),
        ),
    ]
