# Generated by Django 4.2 on 2023-08-30 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_user_bookid_favorites_user_bookid_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bookid_favorites',
        ),
        migrations.AddField(
            model_name='user',
            name='bookid_favorites',
            field=models.ManyToManyField(blank=True, max_length=700, null=True, related_name='bookid_favorites', to='app.book', verbose_name='Избранные книги'),
        ),
    ]
