# Generated by Django 4.2 on 2023-07-18 13:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_user_name_alter_user_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='value',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='bookid',
            field=models.ManyToManyField(blank=True, related_name='bookid', to='app.book', verbose_name='Взятые книги'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bookid_history',
            field=models.ManyToManyField(blank=True, default=None, max_length=1000, related_name='bookid_history', to='app.book', verbose_name='История бронированных книг'),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
