# Generated by Django 4.2 on 2023-09-05 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_user_bookid_favorites_user_bookid_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='bookings',
        ),
        migrations.AlterField(
            model_name='book',
            name='bookmarker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarker_books', to=settings.AUTH_USER_MODEL, verbose_name='Кто добавил в избранное'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bookid_favorites',
            field=models.ManyToManyField(blank=True, max_length=700, null=True, related_name='bookid_favorites_users', to='app.book', verbose_name='Избранные книги'),
        ),
    ]
