# Generated by Django 4.2 on 2023-07-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_user_options_user_image_alter_user_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Гланвый жанр')),
            ],
            options={
                'verbose_name': 'Главный жанр',
                'verbose_name_plural': 'Главные жанры',
            },
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Поджанр', 'verbose_name_plural': 'Поджанры'},
        ),
        migrations.AlterField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='genres', to='app.genre', verbose_name='Поджанры'),
        ),
        migrations.RemoveField(
            model_name='genre',
            name='name',
        ),
        migrations.AddField(
            model_name='genre',
            name='name',
            field=models.ManyToManyField(max_length=150, to='app.maingenre'),
        ),
    ]
