# Generated by Django 4.2 on 2023-07-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_maingenre_alter_genre_options_alter_book_genres_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='name',
        ),
        migrations.AlterField(
            model_name='maingenre',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Гланвый жанр'),
        ),
        migrations.AddField(
            model_name='genre',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
