# Generated by Django 4.2 on 2023-06-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_user_bookid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bookid',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.AddField(
            model_name='user',
            name='bookid',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='id Книг'),
        ),
    ]
