# Generated by Django 4.2 on 2023-07-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_genre_name_alter_maingenre_name_genre_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(blank=True, null=True, related_name='genres', to='app.genre', verbose_name='Поджанры'),
        ),
    ]
