# Generated by Django 4.2 on 2023-07-19 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_book_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maingenre',
            name='name',
        ),
        migrations.AddField(
            model_name='maingenre',
            name='name',
            field=models.ManyToManyField(blank=True, max_length=150, null=True, to='app.genre'),
        ),
    ]
