# Generated by Django 4.2 on 2023-07-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_maingenre_name_maingenre_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='maingenre',
            name='main',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Главный жанр'),
        ),
    ]
