# Generated by Django 4.2 on 2023-06-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_user_bookid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bookid',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='id Книг'),
        ),
    ]
