# Generated by Django 4.2 on 2023-07-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_maingenre_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='genres', to='app.genre', verbose_name='Поджанры'),
        ),
        migrations.AlterField(
            model_name='maingenre',
            name='name',
            field=models.ManyToManyField(blank=True, max_length=150, to='app.genre'),
        ),
    ]
