# Generated by Django 4.2 on 2023-06-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_booking_remove_user_bookid_user_bookid'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='favorites',
            field=models.TextField(blank=True, max_length=10, null=True, verbose_name='Избранное'),
        ),
        migrations.AddField(
            model_name='book',
            name='history',
            field=models.TextField(blank=True, null=True, verbose_name='История бронирования'),
        ),
        migrations.AddField(
            model_name='user',
            name='bookid_favorites',
            field=models.ManyToManyField(blank=True, default=None, max_length=700, related_name='bookid_favorites', to='app.booking', verbose_name='id избранной книги'),
        ),
        migrations.AddField(
            model_name='user',
            name='bookid_history',
            field=models.ManyToManyField(blank=True, default=None, max_length=1000, related_name='bookid_history', to='app.booking', verbose_name='id книги в истории'),
        ),
        migrations.AlterField(
            model_name='book',
            name='bookings',
            field=models.TextField(blank=True, max_length=30, null=True, verbose_name='Бронь книги'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bookid',
            field=models.ManyToManyField(blank=True, default=None, max_length=30, related_name='bookid', to='app.booking', verbose_name='id взятой книги'),
        ),
    ]
