# Generated by Django 4.2 on 2023-07-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_book_genres_alter_maingenre_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на фото акка'),
        ),
    ]
