# Generated by Django 4.2 on 2023-07-08 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_book_favorites_book_history_user_bookid_favorites_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='favorites',
        ),
        migrations.RemoveField(
            model_name='book',
            name='history',
        ),
    ]
