# Generated by Django 4.2 on 2023-07-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_book_favorites_remove_book_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='userid',
        ),
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='book',
            name='review',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bookid_history',
            field=models.ManyToManyField(blank=True, default=None, max_length=1000, related_name='bookid_history', to='app.booking', verbose_name='id бронированных книг в истории'),
        ),
    ]
