# Generated by Django 4.2 on 2023-07-08 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_book_userid_book_rating_book_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Рейтинг'),
        ),
    ]
