# Generated by Django 4.2 on 2023-07-08 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_book_owner_alter_book_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='review',
            field=models.CharField(blank=True, max_length=1500, null=True, verbose_name='Отзыв'),
        ),
    ]
