# Generated by Django 4.2 on 2023-07-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_book_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='bookings',
        ),
        migrations.AddField(
            model_name='book',
            name='bookings',
            field=models.ManyToManyField(blank=True, max_length=30, null=True, to='app.book', verbose_name='Бронь книги'),
        ),
    ]
