# Generated by Django 4.2 on 2023-07-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_remove_book_bookings_book_bookings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookings',
            field=models.ManyToManyField(blank=True, to='app.book', verbose_name='Бронь книги'),
        ),
    ]
