# Generated by Django 4.2 on 2023-07-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_book_bookings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='bookings',
        ),
        migrations.AddField(
            model_name='book',
            name='bookings',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
