# Generated by Django 4.2 on 2023-07-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_book_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bookid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bookid_favorites',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bookid_history',
        ),
        migrations.AddField(
            model_name='user',
            name='bookid',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bookid_favorites',
            field=models.CharField(blank=True, default=None, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bookid_history',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
