# Generated by Django 4.2 on 2023-07-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_remove_book_bookings_remove_user_bookid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bookid',
            field=models.ManyToManyField(blank=True, default=None, max_length=30, related_name='bookid', to='app.book', verbose_name='id взятой книги'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bookid_history',
            field=models.ManyToManyField(blank=True, default=None, max_length=1000, related_name='bookid_history', to='app.book', verbose_name='id бронированных книг в истории'),
        ),
    ]
