# Generated by Django 4.2 on 2023-07-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_user_bookid_alter_user_bookid_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bookid_favorites',
        ),
        migrations.AddField(
            model_name='user',
            name='bookid_favorites',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
    ]
