# Generated by Django 4.2 on 2023-07-11 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_remove_user_bookid_favorites_user_bookid_favorites'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
