# Generated by Django 4.2 on 2023-07-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_delete_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bookid',
            field=models.ManyToManyField(blank=True, related_name='bookid', to='app.book', verbose_name='id взятой книги'),
        ),
    ]
