# Generated by Django 4.2 on 2023-07-11 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_user_bookid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookings',
            field=models.TextField(blank=True, max_length=5, null=True, verbose_name='Бронь книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='genres', to='app.genre', verbose_name='Жанры'),
        ),
        migrations.AlterField(
            model_name='book',
            name='languages',
            field=models.ForeignKey(blank=True, max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='app.language', verbose_name='Языки'),
        ),
        migrations.AlterField(
            model_name='book',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кто забронировал'),
        ),
    ]
