# Generated by Django 4.2 on 2023-07-11 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_remove_book_review_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кто пишет отзыв'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='text',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Комментарий'),
        ),
    ]
