# Generated by Django 4.2 on 2023-07-11 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_reviews_owner_alter_reviews_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
