# Generated by Django 4.2 on 2023-04-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author_name', models.CharField(max_length=50)),
                ('photo', models.TextField()),
                ('description', models.TextField()),
                ('booking_status', models.BooleanField()),
                ('qr_code', models.TextField()),
                ('languag', models.CharField(max_length=50)),
                ('year_publication', models.CharField(max_length=4)),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_book', models.IntegerField()),
                ('id_user', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Genere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GenereBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_book', models.IntegerField()),
                ('id_genre', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_book', models.IntegerField()),
                ('id_user', models.IntegerField()),
                ('date_capture', models.CharField(max_length=4)),
                ('year_delivery', models.CharField(max_length=4)),
                ('recall', models.TextField()),
                ('date_and_time', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('photo', models.TextField()),
                ('user_role', models.BooleanField()),
                ('token', models.TextField()),
            ],
        ),
    ]
