# Generated by Django 4.2 on 2023-04-17 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oggylib_project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='id_book',
        ),
        migrations.AddField(
            model_name='journal',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='oggylib_project.book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='photo',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='qr_code',
            field=models.TextField(null=True),
        ),
    ]
