# Generated by Django 4.2 on 2023-04-17 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oggylib_project', '0002_remove_journal_id_book_journal_book_alter_book_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='id_user',
        ),
        migrations.AddField(
            model_name='journal',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='oggylib_project.users'),
        ),
    ]
