# Generated by Django 4.2 on 2023-04-17 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oggylib_project', '0003_remove_journal_id_user_journal_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='id_book',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='id_user',
        ),
        migrations.RemoveField(
            model_name='generebook',
            name='id_book',
        ),
        migrations.RemoveField(
            model_name='generebook',
            name='id_genre',
        ),
        migrations.AddField(
            model_name='favorite',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='oggylib_project.book'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='oggylib_project.users'),
        ),
        migrations.AddField(
            model_name='generebook',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='oggylib_project.book'),
        ),
        migrations.AddField(
            model_name='generebook',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='oggylib_project.genere'),
        ),
    ]
